//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddAmtTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AddAmtTypeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV12.04}Max12AN">
 *     &lt;enumeration value="Cashback"/>
 *     &lt;enumeration value="Surchrg"/>
 *     &lt;enumeration value="Hltcare"/>
 *     &lt;enumeration value="Transit"/>
 *     &lt;enumeration value="RX"/>
 *     &lt;enumeration value="Vision"/>
 *     &lt;enumeration value="Clinical"/>
 *     &lt;enumeration value="Dental"/>
 *     &lt;enumeration value="Copay"/>
 *     &lt;enumeration value="FirstAuthAmt"/>
 *     &lt;enumeration value="PreAuthAmt"/>
 *     &lt;enumeration value="TotalAuthAmt"/>
 *     &lt;enumeration value="Tax"/>
 *     &lt;enumeration value="Fee"/>
 *     &lt;enumeration value="BegBal"/>
 *     &lt;enumeration value="EndingBal"/>
 *     &lt;enumeration value="AvailBal"/>
 *     &lt;enumeration value="LedgerBal"/>
 *     &lt;enumeration value="HoldBal"/>
 *     &lt;enumeration value="OrigReqAmt"/>
 *     &lt;enumeration value="OpenToBuy"/>
 *     &lt;enumeration value="Fuel"/>
 *     &lt;enumeration value="Service"/>
 *     &lt;enumeration value="eWICDiscount"/>
 *     &lt;enumeration value="TranFee"/>
 *     &lt;enumeration value="OTCReqAmt"/>
 *     &lt;enumeration value="FdReqAmt"/>
 *     &lt;enumeration value="AggDisAmt"/>
 *     &lt;enumeration value="OtherAmt"/>
 *     &lt;enumeration value="OTCApvAmt"/>
 *     &lt;enumeration value="FdApvAmt"/>
 *     &lt;enumeration value="TipAmt"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AddAmtTypeType")
@XmlEnum
public enum AddAmtTypeType {

    @XmlEnumValue("Cashback")
    CASHBACK("Cashback"),
    @XmlEnumValue("Surchrg")
    SURCHRG("Surchrg"),
    @XmlEnumValue("Hltcare")
    HLTCARE("Hltcare"),
    @XmlEnumValue("Transit")
    TRANSIT("Transit"),
    RX("RX"),
    @XmlEnumValue("Vision")
    VISION("Vision"),
    @XmlEnumValue("Clinical")
    CLINICAL("Clinical"),
    @XmlEnumValue("Dental")
    DENTAL("Dental"),
    @XmlEnumValue("Copay")
    COPAY("Copay"),
    @XmlEnumValue("FirstAuthAmt")
    FIRST_AUTH_AMT("FirstAuthAmt"),
    @XmlEnumValue("PreAuthAmt")
    PRE_AUTH_AMT("PreAuthAmt"),
    @XmlEnumValue("TotalAuthAmt")
    TOTAL_AUTH_AMT("TotalAuthAmt"),
    @XmlEnumValue("Tax")
    TAX("Tax"),
    @XmlEnumValue("Fee")
    FEE("Fee"),
    @XmlEnumValue("BegBal")
    BEG_BAL("BegBal"),
    @XmlEnumValue("EndingBal")
    ENDING_BAL("EndingBal"),
    @XmlEnumValue("AvailBal")
    AVAIL_BAL("AvailBal"),
    @XmlEnumValue("LedgerBal")
    LEDGER_BAL("LedgerBal"),
    @XmlEnumValue("HoldBal")
    HOLD_BAL("HoldBal"),
    @XmlEnumValue("OrigReqAmt")
    ORIG_REQ_AMT("OrigReqAmt"),
    @XmlEnumValue("OpenToBuy")
    OPEN_TO_BUY("OpenToBuy"),
    @XmlEnumValue("Fuel")
    FUEL("Fuel"),
    @XmlEnumValue("Service")
    SERVICE("Service"),
    @XmlEnumValue("eWICDiscount")
    E_WIC_DISCOUNT("eWICDiscount"),
    @XmlEnumValue("TranFee")
    TRAN_FEE("TranFee"),
    @XmlEnumValue("OTCReqAmt")
    OTC_REQ_AMT("OTCReqAmt"),
    @XmlEnumValue("FdReqAmt")
    FD_REQ_AMT("FdReqAmt"),
    @XmlEnumValue("AggDisAmt")
    AGG_DIS_AMT("AggDisAmt"),
    @XmlEnumValue("OtherAmt")
    OTHER_AMT("OtherAmt"),
    @XmlEnumValue("OTCApvAmt")
    OTC_APV_AMT("OTCApvAmt"),
    @XmlEnumValue("FdApvAmt")
    FD_APV_AMT("FdApvAmt"),
    @XmlEnumValue("TipAmt")
    TIP_AMT("TipAmt");
    private final String value;

    AddAmtTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AddAmtTypeType fromValue(String v) {
        for (AddAmtTypeType c: AddAmtTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    @Override
    public String toString() {
        return value;
    }
}
