//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthOptGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthOptGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}DfrdAuthTranID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}OverrideInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}AuthOptReasonCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthOptGrp", propOrder = {
    "dfrdAuthTranID",
    "overrideInd",
    "authOptReasonCode"
})
public class AuthOptGrp {

    @XmlElement(name = "DfrdAuthTranID")
    protected String dfrdAuthTranID;
    @XmlElement(name = "OverrideInd")
    @XmlSchemaType(name = "string")
    protected Max3ANYesNo overrideInd;
    @XmlElement(name = "AuthOptReasonCode")
    protected String authOptReasonCode;

    /**
     * Gets the value of the dfrdAuthTranID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDfrdAuthTranID() {
        return dfrdAuthTranID;
    }

    /**
     * Sets the value of the dfrdAuthTranID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDfrdAuthTranID(String value) {
        this.dfrdAuthTranID = value;
    }

    /**
     * Gets the value of the overrideInd property.
     * 
     * @return
     *     possible object is
     *     {@link Max3ANYesNo }
     *     
     */
    public Max3ANYesNo getOverrideInd() {
        return overrideInd;
    }

    /**
     * Sets the value of the overrideInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max3ANYesNo }
     *     
     */
    public void setOverrideInd(Max3ANYesNo value) {
        this.overrideInd = value;
    }

    /**
     * Gets the value of the authOptReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthOptReasonCode() {
        return authOptReasonCode;
    }

    /**
     * Sets the value of the authOptReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthOptReasonCode(String value) {
        this.authOptReasonCode = value;
    }

}
