//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.07.29 at 04:10:17 PM IST 
//


package com.fiserv.merchant.gmfv12;

public enum AVSResultCodeType {

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    I,
    K,
    L,
    M,
    N,
    O,
    P,
    R,
    S,
    U,
    W,
    X,
    Y,
    Z;

    public String value() {
        return name();
    }

    public static AVSResultCodeType fromValue(String v) {
        return valueOf(v);
    }

}
