//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPayGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPayGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}BillPymtTxnInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MerchAdviceCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}InstallInvNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}InstallPymntDesc" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}InstallmentType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MITTotPymtCt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MITAmtType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MITAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MITUniqueID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MITFreq" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MITValFlag" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MITValRef" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}MITSeqInd" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPayGrp", propOrder = {
    "billPymtTxnInd",
    "merchAdviceCode",
    "installInvNum",
    "installPymntDesc",
    "installmentType",
    "mitTotPymtCt",
    "mitAmtType",
    "mitAmt",
    "mitUniqueID",
    "mitFreq",
    "mitValFlag",
    "mitValRef",
    "mitSeqInd"
})
public class BillPayGrp {

    @XmlElement(name = "BillPymtTxnInd")
    @XmlSchemaType(name = "string")
    protected BillPymtTxnIndType billPymtTxnInd;
    @XmlElement(name = "MerchAdviceCode")
    protected String merchAdviceCode;
    @XmlElement(name = "InstallInvNum")
    protected String installInvNum;
    @XmlElement(name = "InstallPymntDesc")
    protected String installPymntDesc;
    @XmlElement(name = "InstallmentType")
    @XmlSchemaType(name = "string")
    protected InstallmentTypeType installmentType;
    @XmlElement(name = "MITTotPymtCt")
    protected String mitTotPymtCt;
    @XmlElement(name = "MITAmtType")
    @XmlSchemaType(name = "string")
    protected MITAmtTypeType mitAmtType;
    @XmlElement(name = "MITAmt")
    protected String mitAmt;
    @XmlElement(name = "MITUniqueID")
    protected String mitUniqueID;
    @XmlElement(name = "MITFreq")
    protected String mitFreq;
    @XmlElement(name = "MITValFlag")
    @XmlSchemaType(name = "string")
    protected MITValFlagType mitValFlag;
    @XmlElement(name = "MITValRef")
    protected String mitValRef;
    @XmlElement(name = "MITSeqInd")
    protected String mitSeqInd;

    /**
     * Gets the value of the billPymtTxnInd property.
     * 
     * @return
     *     possible object is
     *     {@link BillPymtTxnIndType }
     *     
     */
    public BillPymtTxnIndType getBillPymtTxnInd() {
        return billPymtTxnInd;
    }

    /**
     * Sets the value of the billPymtTxnInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillPymtTxnIndType }
     *     
     */
    public void setBillPymtTxnInd(BillPymtTxnIndType value) {
        this.billPymtTxnInd = value;
    }

    /**
     * Gets the value of the merchAdviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchAdviceCode() {
        return merchAdviceCode;
    }

    /**
     * Sets the value of the merchAdviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchAdviceCode(String value) {
        this.merchAdviceCode = value;
    }

    /**
     * Gets the value of the installInvNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallInvNum() {
        return installInvNum;
    }

    /**
     * Sets the value of the installInvNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallInvNum(String value) {
        this.installInvNum = value;
    }

    /**
     * Gets the value of the installPymntDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallPymntDesc() {
        return installPymntDesc;
    }

    /**
     * Sets the value of the installPymntDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallPymntDesc(String value) {
        this.installPymntDesc = value;
    }

    /**
     * Gets the value of the installmentType property.
     * 
     * @return
     *     possible object is
     *     {@link InstallmentTypeType }
     *     
     */
    public InstallmentTypeType getInstallmentType() {
        return installmentType;
    }

    /**
     * Sets the value of the installmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallmentTypeType }
     *     
     */
    public void setInstallmentType(InstallmentTypeType value) {
        this.installmentType = value;
    }

    /**
     * Gets the value of the mitTotPymtCt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITTotPymtCt() {
        return mitTotPymtCt;
    }

    /**
     * Sets the value of the mitTotPymtCt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITTotPymtCt(String value) {
        this.mitTotPymtCt = value;
    }

    /**
     * Gets the value of the mitAmtType property.
     * 
     * @return
     *     possible object is
     *     {@link MITAmtTypeType }
     *     
     */
    public MITAmtTypeType getMITAmtType() {
        return mitAmtType;
    }

    /**
     * Sets the value of the mitAmtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MITAmtTypeType }
     *     
     */
    public void setMITAmtType(MITAmtTypeType value) {
        this.mitAmtType = value;
    }

    /**
     * Gets the value of the mitAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITAmt() {
        return mitAmt;
    }

    /**
     * Sets the value of the mitAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITAmt(String value) {
        this.mitAmt = value;
    }

    /**
     * Gets the value of the mitUniqueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITUniqueID() {
        return mitUniqueID;
    }

    /**
     * Sets the value of the mitUniqueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITUniqueID(String value) {
        this.mitUniqueID = value;
    }

    /**
     * Gets the value of the mitFreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITFreq() {
        return mitFreq;
    }

    /**
     * Sets the value of the mitFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITFreq(String value) {
        this.mitFreq = value;
    }

    /**
     * Gets the value of the mitValFlag property.
     * 
     * @return
     *     possible object is
     *     {@link MITValFlagType }
     *     
     */
    public MITValFlagType getMITValFlag() {
        return mitValFlag;
    }

    /**
     * Sets the value of the mitValFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link MITValFlagType }
     *     
     */
    public void setMITValFlag(MITValFlagType value) {
        this.mitValFlag = value;
    }

    /**
     * Gets the value of the mitValRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITValRef() {
        return mitValRef;
    }

    /**
     * Sets the value of the mitValRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITValRef(String value) {
        this.mitValRef = value;
    }

    /**
     * Gets the value of the mitSeqInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITSeqInd() {
        return mitSeqInd;
    }

    /**
     * Sets the value of the mitSeqInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITSeqInd(String value) {
        this.mitSeqInd = value;
    }

}
