//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DebitGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DebitGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}PayeePhoneNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}PayeeAcctNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}PayeeID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}BillingInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}FPI" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}DbAuthInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}DbStoredCrdnInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}PymtTranID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}PartRefundInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}DbProdCd" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebitGrp", propOrder = {
    "payeePhoneNum",
    "payeeAcctNum",
    "payeeID",
    "billingInd",
    "fpi",
    "dbAuthInd",
    "dbStoredCrdnInd",
    "pymtTranID",
    "partRefundInd",
    "dbProdCd"
})
public class DebitGrp {

    @XmlElement(name = "PayeePhoneNum")
    protected String payeePhoneNum;
    @XmlElement(name = "PayeeAcctNum")
    protected String payeeAcctNum;
    @XmlElement(name = "PayeeID")
    protected String payeeID;
    @XmlElement(name = "BillingInd")
    protected String billingInd;
    @XmlElement(name = "FPI")
    protected String fpi;
    @XmlElement(name = "DbAuthInd")
    @XmlSchemaType(name = "string")
    protected DbAuthIndType dbAuthInd;
    @XmlElement(name = "DbStoredCrdnInd")
    @XmlSchemaType(name = "string")
    protected DbStoredCrdnIndType dbStoredCrdnInd;
    @XmlElement(name = "PymtTranID")
    protected String pymtTranID;
    @XmlElement(name = "PartRefundInd")
    @XmlSchemaType(name = "string")
    protected Max3ANYes partRefundInd;
    @XmlElement(name = "DbProdCd")
    protected String dbProdCd;

    /**
     * Gets the value of the payeePhoneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeePhoneNum() {
        return payeePhoneNum;
    }

    /**
     * Sets the value of the payeePhoneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeePhoneNum(String value) {
        this.payeePhoneNum = value;
    }

    /**
     * Gets the value of the payeeAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeAcctNum() {
        return payeeAcctNum;
    }

    /**
     * Sets the value of the payeeAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeAcctNum(String value) {
        this.payeeAcctNum = value;
    }

    /**
     * Gets the value of the payeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeID() {
        return payeeID;
    }

    /**
     * Sets the value of the payeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeID(String value) {
        this.payeeID = value;
    }

    /**
     * Gets the value of the billingInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingInd() {
        return billingInd;
    }

    /**
     * Sets the value of the billingInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingInd(String value) {
        this.billingInd = value;
    }

    /**
     * Gets the value of the fpi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPI() {
        return fpi;
    }

    /**
     * Sets the value of the fpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPI(String value) {
        this.fpi = value;
    }

    /**
     * Gets the value of the dbAuthInd property.
     * 
     * @return
     *     possible object is
     *     {@link DbAuthIndType }
     *     
     */
    public DbAuthIndType getDbAuthInd() {
        return dbAuthInd;
    }

    /**
     * Sets the value of the dbAuthInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbAuthIndType }
     *     
     */
    public void setDbAuthInd(DbAuthIndType value) {
        this.dbAuthInd = value;
    }

    /**
     * Gets the value of the dbStoredCrdnInd property.
     * 
     * @return
     *     possible object is
     *     {@link DbStoredCrdnIndType }
     *     
     */
    public DbStoredCrdnIndType getDbStoredCrdnInd() {
        return dbStoredCrdnInd;
    }

    /**
     * Sets the value of the dbStoredCrdnInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbStoredCrdnIndType }
     *     
     */
    public void setDbStoredCrdnInd(DbStoredCrdnIndType value) {
        this.dbStoredCrdnInd = value;
    }

    /**
     * Gets the value of the pymtTranID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPymtTranID() {
        return pymtTranID;
    }

    /**
     * Sets the value of the pymtTranID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPymtTranID(String value) {
        this.pymtTranID = value;
    }

    /**
     * Gets the value of the partRefundInd property.
     * 
     * @return
     *     possible object is
     *     {@link Max3ANYes }
     *     
     */
    public Max3ANYes getPartRefundInd() {
        return partRefundInd;
    }

    /**
     * Sets the value of the partRefundInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max3ANYes }
     *     
     */
    public void setPartRefundInd(Max3ANYes value) {
        this.partRefundInd = value;
    }

    /**
     * Gets the value of the dbProdCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbProdCd() {
        return dbProdCd;
    }

    /**
     * Sets the value of the dbProdCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbProdCd(String value) {
        this.dbProdCd = value;
    }

}
