//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnhdFltPromptNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnhdFltPromptNameType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV12.04}Max4AN">
 *     &lt;enumeration value="BDAY"/>
 *     &lt;enumeration value="BLID"/>
 *     &lt;enumeration value="DLIC"/>
 *     &lt;enumeration value="DLST"/>
 *     &lt;enumeration value="DRID"/>
 *     &lt;enumeration value="HBRD"/>
 *     &lt;enumeration value="HRRD"/>
 *     &lt;enumeration value="INVC"/>
 *     &lt;enumeration value="PONB"/>
 *     &lt;enumeration value="TRHB"/>
 *     &lt;enumeration value="TRIP"/>
 *     &lt;enumeration value="TRLR"/>
 *     &lt;enumeration value="UNIT"/>
 *     &lt;enumeration value="XNID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EnhdFltPromptNameType")
@XmlEnum
public enum EnhdFltPromptNameType {

    BDAY,
    BLID,
    DLIC,
    DLST,
    DRID,
    HBRD,
    HRRD,
    INVC,
    PONB,
    TRHB,
    TRIP,
    TRLR,
    UNIT,
    XNID;

    public String value() {
        return name();
    }

    public static EnhdFltPromptNameType fromValue(String v) {
        return valueOf(v);
    }

}
