//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnhdFltPromptGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnhdFltPromptGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}EnhdFltPromptName" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}EnhdFltPromptValue" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}EnhdFltPromptFormat" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnhdFltPromptGrp", propOrder = {
    "enhdFltPromptName",
    "enhdFltPromptValue",
    "enhdFltPromptFormat"
})
public class EnhdFltPromptGrp {

    @XmlElement(name = "EnhdFltPromptName")
    @XmlSchemaType(name = "string")
    protected EnhdFltPromptNameType enhdFltPromptName;
    @XmlElement(name = "EnhdFltPromptValue")
    protected String enhdFltPromptValue;
    @XmlElement(name = "EnhdFltPromptFormat")
    protected String enhdFltPromptFormat;

    /**
     * Gets the value of the enhdFltPromptName property.
     * 
     * @return
     *     possible object is
     *     {@link EnhdFltPromptNameType }
     *     
     */
    public EnhdFltPromptNameType getEnhdFltPromptName() {
        return enhdFltPromptName;
    }

    /**
     * Sets the value of the enhdFltPromptName property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnhdFltPromptNameType }
     *     
     */
    public void setEnhdFltPromptName(EnhdFltPromptNameType value) {
        this.enhdFltPromptName = value;
    }

    /**
     * Gets the value of the enhdFltPromptValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhdFltPromptValue() {
        return enhdFltPromptValue;
    }

    /**
     * Sets the value of the enhdFltPromptValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhdFltPromptValue(String value) {
        this.enhdFltPromptValue = value;
    }

    /**
     * Gets the value of the enhdFltPromptFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhdFltPromptFormat() {
        return enhdFltPromptFormat;
    }

    /**
     * Sets the value of the enhdFltPromptFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhdFltPromptFormat(String value) {
        this.enhdFltPromptFormat = value;
    }

}
