//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FraudMitRespGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FraudMitRespGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}ZipMtch" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}StrMtch" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}NmMtch" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}TeleMtch" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}EmailMtch" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}AddrChg" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}ScoreRes" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}Score" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}RevAt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FraudMitRespGrp", propOrder = {
    "zipMtch",
    "strMtch",
    "nmMtch",
    "teleMtch",
    "emailMtch",
    "addrChg",
    "scoreRes",
    "score",
    "revAt"
})
public class FraudMitRespGrp {

    @XmlElement(name = "ZipMtch")
    protected String zipMtch;
    @XmlElement(name = "StrMtch")
    protected String strMtch;
    @XmlElement(name = "NmMtch")
    protected String nmMtch;
    @XmlElement(name = "TeleMtch")
    protected String teleMtch;
    @XmlElement(name = "EmailMtch")
    protected String emailMtch;
    @XmlElement(name = "AddrChg")
    protected String addrChg;
    @XmlElement(name = "ScoreRes")
    protected String scoreRes;
    @XmlElement(name = "Score")
    protected String score;
    @XmlElement(name = "RevAt")
    protected String revAt;

    /**
     * Gets the value of the zipMtch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipMtch() {
        return zipMtch;
    }

    /**
     * Sets the value of the zipMtch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipMtch(String value) {
        this.zipMtch = value;
    }

    /**
     * Gets the value of the strMtch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrMtch() {
        return strMtch;
    }

    /**
     * Sets the value of the strMtch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrMtch(String value) {
        this.strMtch = value;
    }

    /**
     * Gets the value of the nmMtch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmMtch() {
        return nmMtch;
    }

    /**
     * Sets the value of the nmMtch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmMtch(String value) {
        this.nmMtch = value;
    }

    /**
     * Gets the value of the teleMtch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeleMtch() {
        return teleMtch;
    }

    /**
     * Sets the value of the teleMtch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeleMtch(String value) {
        this.teleMtch = value;
    }

    /**
     * Gets the value of the emailMtch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailMtch() {
        return emailMtch;
    }

    /**
     * Sets the value of the emailMtch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailMtch(String value) {
        this.emailMtch = value;
    }

    /**
     * Gets the value of the addrChg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrChg() {
        return addrChg;
    }

    /**
     * Sets the value of the addrChg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrChg(String value) {
        this.addrChg = value;
    }

    /**
     * Gets the value of the scoreRes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreRes() {
        return scoreRes;
    }

    /**
     * Sets the value of the scoreRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreRes(String value) {
        this.scoreRes = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScore(String value) {
        this.score = value;
    }

    /**
     * Gets the value of the revAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevAt() {
        return revAt;
    }

    /**
     * Sets the value of the revAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevAt(String value) {
        this.revAt = value;
    }

}
