//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstallPymtOptionsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InstallPymtOptionsType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV12.04}Len1AN">
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="B"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InstallPymtOptionsType")
@XmlEnum
public enum InstallPymtOptionsType {

    I,
    F,
    B;

    public String value() {
        return name();
    }

    public static InstallPymtOptionsType fromValue(String v) {
        return valueOf(v);
    }

}
