//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstallmentTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InstallmentTypeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV12.04}Max10AN">
 *     &lt;enumeration value="Merchant"/>
 *     &lt;enumeration value="ThirdParty"/>
 *     &lt;enumeration value="Issuer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InstallmentTypeType")
@XmlEnum
public enum InstallmentTypeType {

    @XmlEnumValue("Merchant")
    MERCHANT("Merchant"),
    @XmlEnumValue("ThirdParty")
    THIRD_PARTY("ThirdParty"),
    @XmlEnumValue("Issuer")
    ISSUER("Issuer");
    private final String value;

    InstallmentTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InstallmentTypeType fromValue(String v) {
        for (InstallmentTypeType c: InstallmentTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
