//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MITValFlagType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MITValFlagType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV12.04}Max12AN">
 *     &lt;enumeration value="Validated"/>
 *     &lt;enumeration value="NotValidated"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MITValFlagType")
@XmlEnum
public enum MITValFlagType {

    @XmlEnumValue("Validated")
    VALIDATED("Validated"),
    @XmlEnumValue("NotValidated")
    NOT_VALIDATED("NotValidated");
    private final String value;

    MITValFlagType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MITValFlagType fromValue(String v) {
        for (MITValFlagType c: MITValFlagType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
