//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MOTOIndicatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MOTOIndicatorType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV12.04}Max10AN">
 *     &lt;enumeration value="MailOrder"/>
 *     &lt;enumeration value="TelPhOrder"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MOTOIndicatorType")
@XmlEnum
public enum MOTOIndicatorType {

    @XmlEnumValue("MailOrder")
    MAIL_ORDER("MailOrder"),
    @XmlEnumValue("TelPhOrder")
    TEL_PH_ORDER("TelPhOrder");
    private final String value;

    MOTOIndicatorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MOTOIndicatorType fromValue(String v) {
        for (MOTOIndicatorType c: MOTOIndicatorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
