//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTRPromptGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OTRPromptGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}OTRPromptName" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}OTRPromptValue" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV12.04}OTRPromptFormat" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OTRPromptGrp", propOrder = {
    "otrPromptName",
    "otrPromptValue",
    "otrPromptFormat"
})
public class OTRPromptGrp {

    @XmlElement(name = "OTRPromptName")
    @XmlSchemaType(name = "string")
    protected OTRPromptNameType otrPromptName;
    @XmlElement(name = "OTRPromptValue")
    protected String otrPromptValue;
    @XmlElement(name = "OTRPromptFormat")
    protected String otrPromptFormat;

    /**
     * Gets the value of the otrPromptName property.
     * 
     * @return
     *     possible object is
     *     {@link OTRPromptNameType }
     *     
     */
    public OTRPromptNameType getOTRPromptName() {
        return otrPromptName;
    }

    /**
     * Sets the value of the otrPromptName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTRPromptNameType }
     *     
     */
    public void setOTRPromptName(OTRPromptNameType value) {
        this.otrPromptName = value;
    }

    /**
     * Gets the value of the otrPromptValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTRPromptValue() {
        return otrPromptValue;
    }

    /**
     * Sets the value of the otrPromptValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTRPromptValue(String value) {
        this.otrPromptValue = value;
    }

    /**
     * Gets the value of the otrPromptFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTRPromptFormat() {
        return otrPromptFormat;
    }

    /**
     * Sets the value of the otrPromptFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTRPromptFormat(String value) {
        this.otrPromptFormat = value;
    }

}
