//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/fiserv/Merchant/gmfV12.04", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fiserv.merchant.gmfv12;
