//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.02 at 12:35:42 PM IST 
//


package com.fiserv.merchant.gmfv12;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TermClassCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TermClassCodeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV12.04}Max13AN">
 *     &lt;enumeration value="mPOSCon"/>
 *     &lt;enumeration value="mPOSSPoCPIN"/>
 *     &lt;enumeration value="mPOSCPoCNoPIN"/>
 *     &lt;enumeration value="mPOSCPoCPIN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TermClassCodeType")
@XmlEnum
public enum TermClassCodeType {

    @XmlEnumValue("mPOSCon")
    M_POS_CON("mPOSCon"),
    @XmlEnumValue("mPOSSPoCPIN")
    M_POSS_PO_CPIN("mPOSSPoCPIN"),
    @XmlEnumValue("mPOSCPoCNoPIN")
    M_POSC_PO_C_NO_PIN("mPOSCPoCNoPIN"),
    @XmlEnumValue("mPOSCPoCPIN")
    M_POSC_PO_CPIN("mPOSCPoCPIN");
    private final String value;

    TermClassCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TermClassCodeType fromValue(String v) {
        for (TermClassCodeType c: TermClassCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
